server:
  port: 8082

spring:
  application:
    name: vault-service

  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/vault_service_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: h6U9t8Wk2z9P5qR4v7M2L0n3B1X8y5A7V9c4G2f1K6E=
  expiration: 86400000
