server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/forgot/**,/api/profile/**,/api/password/forgot/**,/api/password/reset/**,/api/user/**,/api/users/**
            
        - id: vault-service
          uri: lb://vault-service
          predicates:
            - Path=/api/vault/**
          filters:
            - JwtAuthenticationFilter
            
        - id: generator-service
          uri: lb://generator-service
          predicates:
            - Path=/api/generator/**
          filters:
            - JwtAuthenticationFilter
            
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/security/**
          filters:
            - JwtAuthenticationFilter
            
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/otp/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Shared secret key across services
jwt:
  secret: h6U9t8Wk2z9P5qR4v7M2L0n3B1X8y5A7V9c4G2f1K6E=
