server:
  port: 8083

spring:
  application:
    name: generator-service
  config:
    import: "optional:configserver:http://localhost:8888"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: h6U9t8Wk2z9P5qR4v7M2L0n3B1X8y5A7V9c4G2f1K6E=
  expiration: 86400000
